name: Build & Push Docker Image (Release)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract tag
        id: tag
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            TAG="${GITHUB_REF#refs/tags/}"
          else
            TAG=$(git describe --tags --abbrev=0)
          fi
          echo "TAG=$TAG" >> $GITHUB_OUTPUT

      - name: Set image name (lowercase)
        id: image
        run: |
          IMAGE=$(echo "ghcr.io/${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE=$IMAGE" >> $GITHUB_OUTPUT

      - name: Login to GHCR
        run: echo "${{ secrets.GHCR_FERNANDOSORIANO_PAT }}" | docker login ghcr.io -u Fernandosoriano --password-stdin

      # ✅ BUILD (solo un tag)
      - name: Build image
        run: |
          docker build \
            -t ${{ steps.image.outputs.IMAGE }}:${{ steps.tag.outputs.TAG }} \
            .

      # ✅ TAG + PUSH
      - name: Tag & Push image
        run: |
          IMAGE="${{ steps.image.outputs.IMAGE }}"
          VERSION="${{ steps.tag.outputs.TAG }}"

          # push versión
          docker push "$IMAGE:$VERSION"

          # retag a latest
          docker tag "$IMAGE:$VERSION" "$IMAGE:latest"

          # push latest
          docker push "$IMAGE:latest"
